<?

$_MENU_WORKS['en']="Works";
$_MENU_WORKS['pt']="Trabalhos";

$_MENU_SELECTED['en']="Projects";
$_MENU_SELECTED['pt']="Projetos";

$_MENU_ARCHIVE['en']="Archive";
$_MENU_ARCHIVE['pt']="Arquivo";

$_MENU_ARTISTS['en']="Artists";
$_MENU_ARTISTS['pt']="Artistas";

$_MENU_ABOUT['en']="About";
$_MENU_ABOUT['pt']="Sobre";

$_MENU_CONTACT['en']="Contact";
$_MENU_CONTACT['pt']="Contato";

// ------------------------------------------------

$_HOME_WORKS_TITLE['en']="Featured projects";
$_HOME_WORKS_TITLE['pt']="Trabalhos em destaque";

$_HOME_WORKS_DESCRIPTION['en']="Learn about our special projects for brands, companies and advertising. These cases were registered to show every step of M&ouml;ve creative process.";
$_HOME_WORKS_DESCRIPTION['pt']="Learn about our special projects for brands, companies and advertising. These cases were registered to show every step of M&ouml;ve creative process.";

$_HOME_ARTISTS_TITLE['en']="Exclusive artists";
$_HOME_ARTISTS_TITLE['pt']="Artistas exclusivos";

$_HOME_ARTISTS_DESCRIPTION['en']="Learn about our special projects for brands, companies and advertising. These cases were registered to show every step of M&ouml;ve creative process.";
$_HOME_ARTISTS_DESCRIPTION['pt']="Learn about our special projects for brands, companies and advertising. These cases were registered to show every step of M&ouml;ve creative process.";

$_MORE['en']="More &raquo;";
$_MORE['pt']="Mais &raquo;";

// ----------------------------------------------

$_RODAPE['en']='
<p>Porto Alegre +55 51 3012.2491 ::: S&atilde;o Paulo +55 11 2495.9985 :::
<a href="mailto:contato@move.art.br">contato@move.art.br</a><br /> &copy; 2005-2010. All Rights Reserved.</p>
';
$_RODAPE['pt']='
<p>Porto Alegre +55 51 3012.2491 ::: S&atilde;o Paulo +55 11 2495.9985 :::
<a href="mailto:contato@move.art.br">contato@move.art.br</a><br /> &copy; 2005-2010. All Rights Reserved.</p>
';

// -----------------------------------------------

$_VIEW_OPTIONS['en']="View options";
$_VIEW_OPTIONS['pt']="Visualiza&ccedil;&atilde;o";

$_SELECT_BY_TAGS['en']="Select by tags:";
$_SELECT_BY_TAGS['pt']="Filtrar por tags:";

$_WORD_LOCAL['en']="Location";
$_WORD_LOCAL['pt']="Local";

$_WORD_ARTIST['en']="Artist";
$_WORD_ARTIST['pt']="Artista";

$_WORD_PROJECT['en']="Project";
$_WORD_PROJECT['pt']="Projeto";

$_WORD_AGENCY['en']="Commissioned by";
$_WORD_AGENCY['pt']="Comissionado por";

$_WORD_CLIENT['en']="Client";
$_WORD_CLIENT['pt']="Cliente";

$_WORD_SKILLS['en']="Skills";
$_WORD_SKILLS['pt']="Habilidades";

$_WORD_SHARE['en']="Share";
$_WORD_SHARE['pt']="Compartilhar";

$_WORD_TOP['en']="Top";
$_WORD_TOP['pt']="Topo";

$_WORD_NEXT_ARTIST['en']="Next artist &raquo;";
$_WORD_NEXT_ARTIST['pt']="Pr&oacute;ximo artista &raquo;";

$_WORD_NEXT_WORK['en']="Next work &raquo;";
$_WORD_NEXT_WORK['pt']="Pr&oacute;ximo trabalho &raquo;";

$_WORD_PREVIOUS['pt']="&laquo; Anterior";
$_WORD_PREVIOUS['en']="&laquo; Previous";

$_WORD_NEXT['pt']="Pr&oacute;ximo &raquo;";
$_WORD_NEXT['en']="Next &raquo;";

// ----------------------------------------------

?>